# 2015, j.grassler@syseleven.de 
heat_template_version: 2014-10-16

description: >
  Creates a Neutron port on an internal network and associates it with a public
  floating IP address. This template is functionally equivalent to
  `autostrap::floatport::v3`. It merely omits the special OS::stack_id output
  to remain compatible with Juno clouds.

parameters:

  public_net:
    description: UUID of the public network to draw the floating IP address from.
    type: string
  internal_net:
    description: UUID of the internal network to connect ports to.
    type: string
  security_groups:
    type: comma_delimited_list
    description: List of security groups to associate with this port.
    default: []

resources:

  floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: { get_param: public_net }
      port_id: { get_resource: port }

  port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_param: internal_net }
      security_groups: { get_param : security_groups }

outputs:
  floating_ip_address:
    description: The port's allocated floating IP address.
    value: { get_attr: [ floating_ip, floating_ip_address ] }
  port:
    description: The port connected to internal_net.
    value: { get_resource: port }
